apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-2
  labels:
    app: portfolio-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-2
  template:
    metadata:
      labels:
        app: portfolio-2
    spec:
      containers:
        - name: portfolio-2
          image: Aidana-devops/portfolio-2:latest
          ports:
            - containerPort: 80

